// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// field_cohort_sums_cpp
List field_cohort_sums_cpp(NumericVector n, NumericVector d_eff, NumericVector k, NumericVector a10, double B_r, double B_min, double p, double lam, int T, int H, double r);
RcppExport SEXP _BiocharAG_field_cohort_sums_cpp(SEXP nSEXP, SEXP d_effSEXP, SEXP kSEXP, SEXP a10SEXP, SEXP B_rSEXP, SEXP B_minSEXP, SEXP pSEXP, SEXP lamSEXP, SEXP TSEXP, SEXP HSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d_eff(d_effSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a10(a10SEXP);
    Rcpp::traits::input_parameter< double >::type B_r(B_rSEXP);
    Rcpp::traits::input_parameter< double >::type B_min(B_minSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(field_cohort_sums_cpp(n, d_eff, k, a10, B_r, B_min, p, lam, T, H, r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BiocharAG_field_cohort_sums_cpp", (DL_FUNC) &_BiocharAG_field_cohort_sums_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_BiocharAG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
