# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cohort Sums of the Biochar Field Model (Compiled)
#'
#' One dose option of [biochar_field_effects()]: discounted yield-response sums `S_y` and N2O-reduction
#' sums `S_n` per cell, from the two cohort application histories.
#'
#' @param n Cohorts per cell; @param d_eff Effective dose (Mg ha-1); @param k Stock decay rate (yr-1);
#' @param a10 Yield log response ratio at `B_r`.
#' @param B_r,B_min,p Dose-response parameters; @param lam N2O-reduction decay rate (yr-1);
#' @param T Plant life (yr); @param H Horizon (yr); @param r Discount rate.
#' @return List with numeric vectors `S_y` and `S_n`.
#' @keywords internal
field_cohort_sums_cpp <- function(n, d_eff, k, a10, B_r, B_min, p, lam, T, H, r) {
    .Call(`_BiocharAG_field_cohort_sums_cpp`, n, d_eff, k, a10, B_r, B_min, p, lam, T, H, r)
}

